Prserie quickfix for AJAX submissions
fykosak/fksdb pull request #1010
Opened 2021-04-30 06:58 UTC by Jason505Cze

2021-05-02 18:54 UTC, cevro commented on app/Modules/OrgModule/PointsPresenter.php
> +        $this->SQLResultsCache->calculateQuizPoints($contest, $year, $series);
Akú ma pointu to vytiahnuť try-catch bloku?

2021-05-02 18:54 UTC, cevro commented on app/Models/SeriesCalculator.php
> +        if ($contest->contest_id === ModelContest::ID_VYFUK && $year >= 9)
chlpatné zátvorky chýbajú.

2021-05-02 18:59 UTC, cevro commented on app/Models/ORM/Models/modelSubmit.ts
> +    isQuiz: boolean | null;
Je to bool alebo int? Kedy nastáva prípad že tam je null?

2021-05-02 18:59 UTC, cevro commented on app/Components/Controls/AjaxSubmit/Components/Container.tsx
> +            return <p className="alert alert-info">Pro vyplnění kvízu použijte starý systém nahrávání.</p>;
Preklady.

2021-05-02 21:04 UTC, Jason505Cze commented on app/Modules/OrgModule/PointsPresenter.php
> +        $this->SQLResultsCache->calculateQuizPoints($contest, $year, $series);
Špatně commitnutý kód

2021-05-02 21:05 UTC, Jason505Cze commented on app/Models/SeriesCalculator.php
> +        if ($contest->contest_id === ModelContest::ID_VYFUK && $year >= 9)
U jednořádkových akcí je běžné je vynechávat  - ale pokud to vadí, přidám je

2021-05-02 21:16 UTC, Jason505Cze commented on app/Components/Controls/AjaxSubmit/Components/Container.tsx
> +            return <p className="alert alert-info">Pro vyplnění kvízu použijte starý systém nahrávání.</p>;
extract.sh netahá data z tsx souborů, proto to je řešené natvrdo takto.

2021-05-02 21:16 UTC, Jason505Cze commented on app/Models/ORM/Models/modelSubmit.ts
> +    isQuiz: boolean | null;
Byl to případ u starého kódu, moje chyba

2021-05-02 21:28 UTC, cevro commented on app/Models/SeriesCalculator.php
> +        if ($contest->contest_id === ModelContest::ID_VYFUK && $year >= 9)
https://www.php-fig.org/psr/psr-2/

2021-05-02 21:29 UTC, cevro commented on app/Models/ORM/Models/modelSubmit.ts
> +    isQuiz: boolean;
Ešte raz, je to bool alebo int?

2021-05-02 21:29 UTC, cevro commented on app/Components/Controls/AjaxSubmit/Components/Container.tsx
> +            return <p className="alert alert-info">Pro vyplnění kvízu použijte starý systém nahrávání.</p>;
Tak tam majú isť aspoň prekladové značky.

2021-05-02 21:32 UTC, cevro commented
Rýchlim pohľadom som zistil, že nefunguje správne zobrazenie serii pri importe úloh.

2021-05-03 18:57 UTC, Jason505Cze commented
Jak přesně nefunguje? Nevidím nic co by nefungovalo.

2021-05-03 19:05 UTC, Jason505Cze commented on app/Models/ORM/Models/modelSubmit.ts
> +    isQuiz: boolean;
Je to bool, upravil jsem kód aby byl korektní.

2021-05-03 19:34 UTC, cevro commented
![Screenshot_2021-05-03_21-25-32](https://user-images.githubusercontent.com/10603313/116923761-4f72fc00-ac57-11eb-8ef4-29d933446176.png)

Je tak len 5. sérii.

2021-05-03 19:57 UTC, cevro commented on app/Components/Controls/AjaxSubmit/Components/Container.tsx
> +            return <p className="alert alert-info">{('Pro vyplnění kvízu použijte starý systém nahrávání.')}</p>;
https://github.com/fykosak/fksdb/wiki/Frontend-localization

2021-05-03 19:58 UTC, cevro commented on app/Models/ORM/Services/ServiceSubmit.php
> +        $test = count($task->related(DbNames::TAB_QUIZ));
Nejaký fragment z testovania?

2021-05-03 20:22 UTC, Jason505Cze commented on app/Components/Controls/AjaxSubmit/Components/Container.tsx
> +            return <p className="alert alert-info">{('Pro vyplnění kvízu použijte starý systém nahrávání.')}</p>;
Četl jsem dokumentaci, stejně se to pak bude muset přepsat protože ID je česky a ne anglicky.

2021-05-03 20:37 UTC, cevro commented on app/Components/Controls/AjaxSubmit/Components/Container.tsx
> +            return <p className="alert alert-info">{('Pro vyplnění kvízu použijte starý systém nahrávání.')}</p>;
Hlavne je potrebné aby to bolo v prekladových značkách, a potom sa na to myslelo pri prekladoch, pretože ešte stále niesú všetky dokončené, nech skľudom to je aj po česky, to nieje až taký problém.

2021-05-06 19:54 UTC, cevro requested changes
Vyzerá, že ` www/js/bundle.min.js` je neminimalizovaný a preložený cez `dev` namiesto `build`

2021-05-07 11:16 UTC, Jason505Cze commented on app/Models/SeriesCalculator.php
> +        if ($contest->contest_id === ModelContest::ID_VYFUK && $year >= 9)
vyřešeno

2021-05-07 11:20 UTC, cevro approved these changes

2021-05-07 11:24 UTC, merged