team rank sorting
fykosak/fksdb pull request #1296
Opened 2023-02-22 13:24 UTC by cevro

2023-02-23 23:15 UTC, Werkov commented on app/Components/Game/Diplomas/RankingStrategy.php
> -                    return (int)($qa - $qb);
Hm, this might have been the problem -- when `0 < $qa-$qb < 1`, it'd be truncated to 0, comparing two entries as equal. But it's not symmetric. So rather consider averages closer than 1 sorted pseudorandomly.

2023-02-24 00:01 UTC, Werkov requested changes

2023-02-24 00:02 UTC, Werkov commented
You may want to add tests for the RankingStrategy or at least for the comparing function with some simple yet defining examples.

2023-02-25 01:19 UTC, Headary commented on app/Components/Game/Diplomas/RankingStrategy.php
> -                    return (int)($qa - $qb);
Addressed by comparing only the submit counts because at this step, points must be equal so comparing only the denominators is enough.

2023-02-25 01:21 UTC, Headary commented on app/Components/Game/Diplomas/RankingStrategy.php
> +            }
Change to `team->created`.

2023-02-26 04:51 UTC, cevro commented on app/Components/Game/Diplomas/RankingStrategy.php
> +            }
Robíte v tom chaos, pri tvorení pravidiel sa povedalo, že sa to bude rozhodovať, podľa `team_id`. @Headary to mal pôvodne správne.

Dá sa na to použiť raketa, kedže je to posledná podmienka `team_id <=> team_id`

2023-02-26 04:51 UTC, cevro commented on app/Components/Game/Diplomas/RankingStrategy.php
> +    public function getInvalidTeamsPoints(?TeamCategory $category = null): array
Časom presunúť do ClosingStrategy resp. ClosingHandler v https://github.com/fykosak/fksdb/pull/1294/files#diff-7827639e5cf009a0a7eec6c6cf52a3cd9361d8727e3850ee76aac92e802b7bae

Dobré je rozlišovať, uzatváranie bodovania tímu a napočítavanie poradia tímov, a mať ich aj v kóde rozlíšené a oddelené.

2023-02-26 04:56 UTC, cevro commented on app/Components/Game/Diplomas/RankingStrategy.php
> +        $submitPointsCount = array_fill(0, $maxPoints + 1, 0);
Funkcia na parsovanie available_points už existuje:
https://github.com/fykosak/fksdb/blob/master/app/Models/ORM/Models/Fyziklani/GameSetupModel.php#L25

Použiť tú a neduplikovať funkcionalitu.

`array_fill` je nesprávny má sa použiť na inicializáciu foreach($availablePoints...), takto inicializuje pole aj s bodmi, ktoré tím nemôže podľa pravidiel získať.

2023-02-26 06:58 UTC, cevro commented on app/Components/Game/Diplomas/RankingStrategy.php
> +            if (!is_null($category)) {
je to `function` musíš použíť pre dodanie contextu `use($category)`.

2023-02-26 21:01 UTC, Headary commented on app/Components/Game/Diplomas/RankingStrategy.php
> +            }
On tam je taky problém v tom, že pokud se rozhoduje podle vytvoření, tak to stále může být stejné a tedy nejasné, kdo by měl být výš. V pravidlech stojí, že v případě shody rozhodne náhodný los, ale tím získáváme sort, který nemusí dopadnout vždy stejně a není to moc dobrý. Řadil bych to tedy podle `team_id` a v pravidla upravil do formy "Pokud o pořadí týmu ve výsledkové listině nerozhodne počet bodů...nižší týmový koeficient a pořadí vytvoření týmů".

2023-02-26 23:25 UTC, Werkov commented on app/Components/Game/Diplomas/RankingStrategy.php
> +            }
Jasně, já jsem jen chtěl upozornit, že to id nemusí odpovídat pořadí vytvoření týmu (z pohledu uživatele).

2023-02-26 23:48 UTC, Werkov commented on tests/ComponentTests/Game/Diplomas/RankingStrategyTest.phpt
> +            [5, 2, 1], // more 5 point submits
4 vs 8/3=2.67 rozdíl průměru více než 1,
pro pocit sucha a jistoty bych přidal i dvojici, kde je rozdíl průměrů menší než 1.

2023-02-26 23:48 UTC, Werkov commented on app/Components/Game/Diplomas/RankingStrategy.php
> +    public function getInvalidTeamsRank(?TeamCategory $category = null): array
Vidím tuhle funkci použitou v testech i v diplomovacím kódu.
Testy a funhční kód by měly být nezávislé.
Takhle v tom testu není jasné, jestli se testuje `getInvalidTeamsRank()` anebo `RankingStrategy::close()`. (Podobně jak píše @cevro u `getInvalidTeamsPoints()`.)
V testu by měl být jen trivální porovnání oproti tomu definičnímu poli `teamSubmitPoints`.

2023-02-26 23:48 UTC, Werkov approved these changes

2023-02-27 03:58 UTC, cevro commented on app/Components/Game/Diplomas/RankingStrategy.php
> +            }
,Pravidla vs ich interná implentacia su 2 rôzne veci, to ze je v pravidlách daný skorší dátum prihlásenia znamená reálne nižšie team_id, pretoze team_id sa získava pri vytvorení tímu. Teda kto skor príde dostane nižšie team_id. Do pravidiel by som nic ako team_id netahal a nespomínal. My vieme ze toto je stabilne a dobre definované, pravidla to vedieť nemusia a napr pre iné systemy s tym môže byt problem. Los je náhodný a astabilny teda nemusí dopadnúť rovnako vždy. A z definície toho ze narozdiel od create je toto naozaj férové a jednoznačne by som používal tesm_id.

2023-03-03 14:45 UTC, cevro commented on tests/ComponentTests/Game/Diplomas/RankingStrategyTest.phpt
> +    private RankingStrategy $rankingStrategy;
@Headary toto som myslel, tu sa nastavovali dynamicky.

2023-03-06 11:59 UTC, merged