Add oauth2 for google
fykosak/fksdb pull request #884
Opened 2020-10-03 22:22 UTC by cevro

2020-10-04 15:34 UTC, Werkov requested changes
Some more and less relevant notes are in the code.
Two general questions:
- Is FacebookAuthenticator still working? Is it used?
- How is ensured that only FYKOS organization accounts can be used to gain "org" access (and not anyone with their Google account)?

2020-10-04 15:34 UTC, Werkov commented on app/Modules/CoreModule/presenters/AuthenticationPresenter.php
> +    private Google $provider;
More descriptive name, perhaps `$googleProvider`? But see below my note about it.

2020-10-04 15:34 UTC, Werkov commented on app/Modules/CoreModule/presenters/AuthenticationPresenter.php
> +    protected function getGoogleOAuth2Provider(): Google {
Wouldn't it make more sense to inject the whole `Google` class instance via standard dependency injection and defined in `services.neon`?

2020-10-04 15:34 UTC, Werkov commented on app/model/Authentication/GoogleAuthenticator.php
> + * @author Michal Koutný <michal@fykos.cz>
Please, don't copy-paste my authorship to newly created classes.

2020-10-04 15:34 UTC, Werkov commented on app/model/Authentication/GoogleAuthenticator.php
> +            throw new AuthenticationException(_('V profilu google nebyl nalezen e-mail.'));
s/google/Google/

2020-10-04 15:34 UTC, Werkov commented on app/model/Authentication/GoogleAuthenticator.php
> +         return $result;*/
Drop this.

2020-10-04 15:34 UTC, Werkov commented on app/model/WebService/WebServiceModel.php
> +    private PasswordAuthenticator $authenticator;
Good change.

2020-10-04 15:34 UTC, Werkov commented on app/model/Authentication/GoogleAuthenticator.php
> +                $login = $this->accountManager->createLogin($person);
Is it intended that org-level accounts are created automatically?

2020-10-04 15:34 UTC, Werkov commented on app/Modules/CoreModule/templates/Authentication/login.latte
> +        <a class="btn btn-secondary btn-sm btn-block" href="{link google!}"><i class="fa fa-google mr-3"/>{_'Login via FYKOS account on Google'}</a>
Are the canonical labels in English or Czech?

2020-10-04 15:34 UTC, Werkov commented on app/model/Authentication/GoogleAuthenticator.php
> +            case 'vyfuk.org':
This domain doesn't seem to be handled by G Suite.

2020-10-04 15:57 UTC, cevro commented on app/Modules/CoreModule/presenters/AuthenticationPresenter.php
> +    protected function getGoogleOAuth2Provider(): Google {
Nice idea, but in constructor Google(provider) you require redirect link, that's mean, you need presenter to create instance of Google(provider). Of course you can create `Factory` with method `create(IPresenter):Google`, but it's IMO over-kill, cause  google is used only in single Presenter.

2020-10-04 15:58 UTC, cevro commented on app/model/Authentication/GoogleAuthenticator.php
> + * @author Michal Koutný <michal@fykos.cz>
Sry, I fix it,
...but core of this factory is your own code.

2020-10-04 16:00 UTC, cevro commented on app/model/Authentication/GoogleAuthenticator.php
> +         return $result;*/
Its prepare for using google outside of FYKOS google accounts.

2020-10-04 16:05 UTC, cevro commented on app/model/Authentication/GoogleAuthenticator.php
> +                $login = $this->accountManager->createLogin($person);
Its only record in table `login`, records in tables `person*` and `org` will be created as before, accManager should not create it.

2020-10-04 16:06 UTC, cevro commented on app/Modules/CoreModule/templates/Authentication/login.latte
> +        <a class="btn btn-secondary btn-sm btn-block" href="{link google!}"><i class="fa fa-google mr-3"/>{_'Login via FYKOS account on Google'}</a>
Canonical is English, but it's still many places where isn't.

2020-10-04 16:07 UTC, cevro commented on app/model/Authentication/GoogleAuthenticator.php
> +            case 'vyfuk.org':
Answer in email.

2020-10-04 16:18 UTC, cevro commented
@Werkov 

> Is FacebookAuthenticator still working? Is it used?
No, not working approx 4-5 years, expire FB SDK, and anybody didn't fix it, but code is still in FKSDB and probably is still registered as service.

> How is ensured that only FYKOS organization accounts can be used to gain "org" access (and not anyone with their Google account)?
App ID is registered only for FYKOS's G Suite, and it's possible restrict users only for domain. If will works fine, I remove restriction and allow login for all google users.

2020-10-04 16:52 UTC, Werkov commented on app/model/Authentication/GoogleAuthenticator.php
> +                $login = $this->accountManager->createLogin($person);
Fair enough.

2020-10-04 16:53 UTC, Werkov commented on app/model/Authentication/GoogleAuthenticator.php
> +         return $result;*/
I'd suggest keeping it in a (future) separate commit, without the comment in the current code.

2020-10-04 16:54 UTC, Werkov commented on app/model/Authentication/GoogleAuthenticator.php
> + * @author Michal Koutný <michal@fykos.cz>
I believe it's just the skeleton, the meat is yours. Feel free to remove my attribution.

2020-10-04 17:19 UTC, Werkov commented on app/Modules/CoreModule/presenters/AuthenticationPresenter.php
> +    protected function getGoogleOAuth2Provider(): Google {
I missed the link dependency. What about https://api.nette.org/2.4/Nette.Application.LinkGenerator.html?

2020-10-04 17:21 UTC, Werkov commented
Thanks for the explanation. Ad FB authenticator, I'd suggest delete it (with roots) so that there is less dead/vulnerable code in the auth area.

2020-10-04 19:08 UTC, cevro commented on app/model/Authentication/GoogleAuthenticator.php
> + * @author Michal Koutný <michal@fykos.cz>
Well, it's done.

2020-10-04 21:47 UTC, cevro commented on app/Modules/CoreModule/presenters/AuthenticationPresenter.php
> +    protected function getGoogleOAuth2Provider(): Google {
Good point, I use LinkGenerator in some factories, there are some positives/negatives link has to be always absolute and, and starting ':' has to be omitted. There is a big incompatibility between links in Presenters and LinkGenerator. But I tried it, and looks fine.

2020-10-06 12:10 UTC, sstenchlak approved these changes

2020-10-06 12:10 UTC, sstenchlak commented on app/model/Authentication/GoogleAuthenticator.php
> +                throw new InvalidCredentialsException();
I would prefer something like 'This e-mail address is not linked to an **organizer** account' exception to emphasize that this option is not for contestants.

2020-10-06 12:43 UTC, sstenchlak approved these changes

2020-10-07 22:06 UTC, merged