SOAP signatures
fykosak/fksdb pull request #978
Opened 2021-03-08 19:59 UTC by cevro

## Input 
```xml 
....
    <SOAP-ENV:Body>
        <GetSignaturesRequest>
            <contestId>1</contestId>
        </GetSignaturesRequest>
    </SOAP-ENV:Body>
...
```

## Output

```xml
...
<SOAP-ENV:Body>
<signatures>
  <org>
    <name>Full Name</name>
    <texSignature>texSignature</texSignature>
    <domainAlias>domainAlias</domainAlias>
  </org>
  <org>
    <name>Full Name</name>
    <texSignature>texSignature</texSignature>
    <domainAlias></domainAlias>
  </org>
...
</signatures>
</SOAP-ENV:Body>
...
```

2021-03-08 21:27 UTC, Headary commented
Je potřeba si dát pozor, aby byli změny ve FKSDB a makrech implementovány stejně kvůli request templatu a xslt. Implementace tvých změn jsem navrhl v https://github.com/fykosak/fks-templates/pull/23 a https://github.com/fykosak/fks-scripts/pull/18 .

2021-03-08 21:40 UTC, rzehumat reviewed
Čitelnost kódu (naming, casing, intendation) IMO velmi dobrá. 
Víc nedám, `php` vidím asi _podruhé v životě_.

2021-03-08 21:51 UTC, sstenchlak requested changes
Dostávám `Procedure 'GetSignaturesRequest' not present` v `app/Models/WebService/SoapResponse.php:24`. Dělám něco špatně?

2021-03-08 22:42 UTC, cevro commented
@sstenchlak 

> Dělám něco špatně?
Ano, FKSDB nezávisle na tom kde beží sa dotazuje na wsdl stále na produkciu.
Teda potreba vytiahnuť  do `config.local.neon` `wsdlUrl: http://db.fykos.local/FKSDBWebServices.wsdl`
Potom si treba ručne prepísať https://github.com/fykosak/fksdb/pull/978/files#diff-193b20afa46db38346e0f764860547cb54aeb9c7654570cad64e96afa8a310e8L252 opäť na svoju instanciu a doporučujem ešte v php.ini nastaviť nulový čas expiracie cache. SOAP je neuveriteľne drzí čo sa tíka cachovania.

2021-03-08 22:44 UTC, cevro commented
@Headary export som ešte nezmazal a ani to neplánujem dokedy si nebudeme istý, že to nič nerozbije a toto bude plne funkčné.

2021-04-06 22:25 UTC, cevro commented
Otestoval som to u seba, a vyzerá že všetky WS fungujú, teda to namergujem, nech sa môže pohnúť práca dalej.

Spolu s tým vydám aj novú verziu FKSDB-downloader-core, kde je aj nástroj na sťahovanie týchto requestov.

2021-04-06 22:25 UTC, merged