Translations to en
fykosak/fksdb pull request #985
Opened 2021-03-14 13:52 UTC by vanekm

2021-03-14 17:14 UTC, cevro commented on app/Models/ORM/Columns/Tables/Schedule/ScheduleGroup/ScheduleGroupTypeRow.php
> +<?php
Tento súbor je čisto pridaný. Potreba zmazať.

2021-03-14 17:15 UTC, cevro commented on composer-setup.php
> +<?php
Odstrániť tento súbor.

2021-03-14 17:17 UTC, cevro requested changes
Ešte potom treba zmazať composer.phar

2021-03-15 14:40 UTC, vanekm commented
Přebytečné soubory smazány.

2021-03-15 15:57 UTC, cevro approved these changes

2021-03-16 16:46 UTC, merged